# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 02:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_body', ckeditor.fields.RichTextField()),
                ('article_slug', models.SlugField(max_length=200, unique=True)),
                ('article_publish', models.BooleanField(default=False)),
                ('article_created', models.DateTimeField(auto_now_add=True)),
                ('article_modified', models.DateTimeField(auto_now=True)),
                ('article_url', models.URLField(blank=True, max_length=250, verbose_name='URL')),
                ('article_coverurl', models.URLField(blank=True, max_length=250)),
                ('article_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog Entry',
                'ordering': ['-article_created'],
                'verbose_name_plural': 'Blog Entries',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('suf', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('other_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('twitter', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to='blog.Author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to='blog.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='article_coverurl',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, max_length=250, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='author',
            name='publication',
            field=models.ManyToManyField(through='blog.Roles', to='blog.Publication'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_authors',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_authorsroles',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Roles'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_publication_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Publication'),
        ),
        migrations.AddField(
            model_name='post',
            name='article_authors',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Author'),
        ),
        migrations.AddField(
            model_name='post',
            name='article_authorsroles',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Roles'),
        ),
        migrations.AddField(
            model_name='post',
            name='article_publication_name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Publication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='category_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
            preserve_default=False,
        ),
    ]
